version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      timezone: "Europe/Amsterdam"
      time: "01:00"
    # To disable, set to 0. Default (unset) is 5
    open-pull-requests-limit: 3
