ENABLE: MARKDOWN
ENABLE_LINTERS: JSON_PRETTIER, YAML_PRETTIER, BASH_EXEC, SPELL_CSPELL
MARKDOWN_MARKDOWN_LINK_CHECK_DISABLE_ERRORS: true
FILTER_REGEX_EXCLUDE: (src/|.github/linters/)
IGNORE_GENERATED_FILES: true
IGNORE_GITIGNORED_FILES: true