apiVersion: constraints.gatekeeper.sh/v1beta1
kind: SbomVerification
metadata:
  name: sbom-validation
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces:
      - "default"
  parameters:
    issuer: "CN=ca.example.com,OU=My Org,O=My Company,L=Redmond,ST=WA,C=US"