apiVersion: config.ratify.deislabs.io/v1beta1
kind: Verifier
metadata:
  name: verifier-vuln
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "5"
spec:
  name: vulnerabilityreport
  artifactTypes: application/sarif+json
  parameters:
    nestedReferences: application/vnd.cncf.notary.signature
    maximumAge: 24h