apiVersion: config.ratify.deislabs.io/v1alpha1
kind: Verifier
metadata:
  name: verifier-trivy
spec:
  name: schemavalidator
  artifactTypes: application/trivy+json
  parameters: 
    nestedReferences: application/vnd.cncf.notary.signature
    schemas:
      application/sarif+json: https://json.schemastore.org/sarif-2.1.0-rtm.5.json